name: Set New Version Tag

on:
  push:
    branches:
      - master

jobs:
  set-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Version Tag
        run: |
          make set_new_version_tag

  trigger-build-CIs:
    needs: set-version-tag
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Python Build CI
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ github.token }}
        repository: ECTLab/AIaaS-gRPC-protos
        event-type: tag-created
        client-payload: '{"tag_name": "$(git tag --sort=-version:refname --list `v[0-9]*.[0-9]*.[0-9]*` | head -n1)"}'
