name: Set New Version Tag

on:
  push:
    branches:
      - master

jobs:
  set-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Version Tag
        run: |
          make set_new_version_tag

  trigger-build-CIs:
    needs: set-version-tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Send tag-created event
      run: |
        git fetch --tags
        export LAST_TAG=$(git tag --sort=-version:refname --list 'v[0-9]*.[0-9]*.[0-9]*' | head -n1)
        echo "LAST_TAG=$LAST_TAG"
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ github.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/ECTLab/AIaaS-gRPC-protos/dispatches \
        -d '{"event_type":"tag-created","client_payload":{"tag_name":"'"$LAST_TAG"'"}}'
